#!/bin/bash

# Setup Development Environment for Pakkt Backend
# This script helps you create .dev.vars with proper Supabase credentials

set -e

echo "🚀 Pakkt Backend Environment Setup"
echo "===================================="
echo ""

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Check if Supabase is running
echo "📡 Checking if Supabase is running..."
cd "$PROJECT_ROOT/.."
if ! supabase status &>/dev/null; then
    echo "❌ Supabase is not running!"
    echo ""
    echo "Please start Supabase first:"
    echo "  cd $(pwd)"
    echo "  supabase start"
    echo ""
    exit 1
fi

echo "✅ Supabase is running!"
echo ""

# Get Supabase credentials
echo "🔑 Fetching Supabase credentials..."
SUPABASE_STATUS=$(supabase status)

SUPABASE_URL=$(echo "$SUPABASE_STATUS" | grep "API URL:" | awk '{print $3}')
ANON_KEY=$(echo "$SUPABASE_STATUS" | grep "anon key:" | awk '{print $3}')
SERVICE_ROLE_KEY=$(echo "$SUPABASE_STATUS" | grep "service_role key:" | awk '{print $3}')

cd "$PROJECT_ROOT"

# Create .dev.vars file
echo "📝 Creating .dev.vars file..."
cat > .dev.vars << EOF
# Cloudflare Workers Development Environment Variables
# Generated by setup-env.sh on $(date)
# DO NOT commit this file to git!

# Supabase Configuration
SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY

# Environment
ENVIRONMENT=development
EOF

echo "✅ .dev.vars created successfully!"
echo ""
echo "📋 Your configuration:"
echo "  Supabase URL: $SUPABASE_URL"
echo "  Anon Key: ${ANON_KEY:0:20}..."
echo "  Service Role Key: ${SERVICE_ROLE_KEY:0:20}..."
echo ""
echo "⚠️  Security Note:"
echo "  - .dev.vars contains sensitive credentials"
echo "  - It's already in .gitignore"
echo "  - NEVER commit it to version control"
echo ""
echo "✅ Setup complete! You can now:"
echo "  1. cd /Users/rinshin/Code/pakkt/backend"
echo "  2. npm run dev"
echo "  3. Use scripts/get-auth-token.sh to get test tokens"
echo ""
